import type { Metadata } from "next";
import { IBM_Plex_Sans, Inter } from "next/font/google";
import { TabNav } from "./components/tab/Tab";
import Header from "next/head";
import "./globals.css";
import Provider from "@/context/Provider";
const ibmPlexSans = IBM_Plex_Sans({
  variable: "--font-ibm-plex-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});
const interFont = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});
// deployment
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" className={`${ibmPlexSans.variable} ${interFont.variable}`}>
      <body
        className={`${ibmPlexSans.variable}  antialiased bg-[#101010] text-white`}
      >
        <Header>
          <script src="/telegram-web-app.js"></script>
        </Header>
        <Provider>{children}</Provider>
        <TabNav />
      </body>
    </html>
  );
}
